# Maps FS ST code -> SUVR region column name
ST_TO_SUVR_REGION = {
    # ---- Left Hemisphere Cortical (33 regions) ----
    "ST13":  "CTX_LH_BANKSSTS",
    "ST14":  "CTX_LH_CAUDALANTERIORCINGULATE",
    "ST15":  "CTX_LH_CAUDALMIDDLEFRONTAL",
    "ST23":  "CTX_LH_CUNEUS",
    "ST24":  "CTX_LH_ENTORHINAL",
    "ST25":  "CTX_LH_FRONTALPOLE",
    "ST26":  "CTX_LH_FUSIFORM",
    "ST31":  "CTX_LH_INFERIORPARIETAL",
    "ST32":  "CTX_LH_INFERIORTEMPORAL",
    "ST34":  "CTX_LH_ISTHMUSCINGULATE",
    "ST35":  "CTX_LH_LATERALOCCIPITAL",
    "ST36":  "CTX_LH_LATERALORBITOFRONTAL",
    "ST38":  "CTX_LH_LINGUAL",
    "ST39":  "CTX_LH_MEDIALORBITOFRONTAL",
    "ST40":  "CTX_LH_MIDDLETEMPORAL",
    "ST43":  "CTX_LH_PARACENTRAL",
    "ST44":  "CTX_LH_PARAHIPPOCAMPAL",
    "ST45":  "CTX_LH_PARSOPERCULARIS",
    "ST46":  "CTX_LH_PARSORBITALIS",
    "ST47":  "CTX_LH_PARSTRIANGULARIS",
    "ST48":  "CTX_LH_PERICALCARINE",
    "ST49":  "CTX_LH_POSTCENTRAL",
    "ST50":  "CTX_LH_POSTERIORCINGULATE",
    "ST51":  "CTX_LH_PRECENTRAL",
    "ST52":  "CTX_LH_PRECUNEUS",
    "ST54":  "CTX_LH_ROSTRALANTERIORCINGULATE",
    "ST55":  "CTX_LH_ROSTRALMIDDLEFRONTAL",
    "ST56":  "CTX_LH_SUPERIORFRONTAL",
    "ST57":  "CTX_LH_SUPERIORPARIETAL",
    "ST58":  "CTX_LH_SUPERIORTEMPORAL",
    "ST59":  "CTX_LH_SUPRAMARGINAL",
    "ST60":  "CTX_LH_TEMPORALPOLE",
    "ST62":  "CTX_LH_TRANSVERSETEMPORAL",
    
    # ---- Right Hemisphere Cortical (33 regions) ----
    "ST72":  "CTX_RH_BANKSSTS",
    "ST73":  "CTX_RH_CAUDALANTERIORCINGULATE",
    "ST74":  "CTX_RH_CAUDALMIDDLEFRONTAL",
    "ST82":  "CTX_RH_CUNEUS",
    "ST83":  "CTX_RH_ENTORHINAL",
    "ST84":  "CTX_RH_FRONTALPOLE",
    "ST85":  "CTX_RH_FUSIFORM",
    "ST90":  "CTX_RH_INFERIORPARIETAL",
    "ST91":  "CTX_RH_INFERIORTEMPORAL",
    "ST93":  "CTX_RH_ISTHMUSCINGULATE",
    "ST94":  "CTX_RH_LATERALOCCIPITAL",
    "ST95":  "CTX_RH_LATERALORBITOFRONTAL",
    "ST97":  "CTX_RH_LINGUAL",
    "ST98":  "CTX_RH_MEDIALORBITOFRONTAL",
    "ST99":  "CTX_RH_MIDDLETEMPORAL",
    "ST102": "CTX_RH_PARACENTRAL",
    "ST103": "CTX_RH_PARAHIPPOCAMPAL",
    "ST104": "CTX_RH_PARSOPERCULARIS",
    "ST105": "CTX_RH_PARSORBITALIS",
    "ST106": "CTX_RH_PARSTRIANGULARIS",
    "ST107": "CTX_RH_PERICALCARINE",
    "ST108": "CTX_RH_POSTCENTRAL",
    "ST109": "CTX_RH_POSTERIORCINGULATE",
    "ST110": "CTX_RH_PRECENTRAL",
    "ST111": "CTX_RH_PRECUNEUS",
    "ST113": "CTX_RH_ROSTRALANTERIORCINGULATE",
    "ST114": "CTX_RH_ROSTRALMIDDLEFRONTAL",
    "ST115": "CTX_RH_SUPERIORFRONTAL",
    "ST116": "CTX_RH_SUPERIORPARIETAL",
    "ST117": "CTX_RH_SUPERIORTEMPORAL",
    "ST118": "CTX_RH_SUPRAMARGINAL",
    "ST119": "CTX_RH_TEMPORALPOLE",
    "ST121": "CTX_RH_TRANSVERSETEMPORAL",
}

# Maps SUVR region name -> Braak stage index
# 0 = early (I/II), 1 = middle (III/IV), 2 = late (V/VI)
REGION_TO_BRAAK = {
    # Stage I/II (early)
    "CTX_LH_ENTORHINAL": 0, "CTX_RH_ENTORHINAL": 0,
    "CTX_LH_PARAHIPPOCAMPAL": 0, "CTX_RH_PARAHIPPOCAMPAL": 0,
    
    # Stage III/IV (middle)
    "CTX_LH_FUSIFORM": 1, "CTX_RH_FUSIFORM": 1,
    "CTX_LH_LINGUAL": 1, "CTX_RH_LINGUAL": 1,
    "CTX_LH_INFERIORTEMPORAL": 1, "CTX_RH_INFERIORTEMPORAL": 1,
    "CTX_LH_MIDDLETEMPORAL": 1, "CTX_RH_MIDDLETEMPORAL": 1,
    "CTX_LH_POSTERIORCINGULATE": 1, "CTX_RH_POSTERIORCINGULATE": 1,
    "CTX_LH_ISTHMUSCINGULATE": 1, "CTX_RH_ISTHMUSCINGULATE": 1,
    "CTX_LH_BANKSSTS": 1, "CTX_RH_BANKSSTS": 1,
    "CTX_LH_TEMPORALPOLE": 1, "CTX_RH_TEMPORALPOLE": 1,
    "CTX_LH_TRANSVERSETEMPORAL": 1, "CTX_RH_TRANSVERSETEMPORAL": 1,
    
    # Stage V/VI (late)
    "CTX_LH_INFERIORPARIETAL": 2, "CTX_RH_INFERIORPARIETAL": 2,
    "CTX_LH_SUPERIORPARIETAL": 2, "CTX_RH_SUPERIORPARIETAL": 2,
    "CTX_LH_PRECUNEUS": 2, "CTX_RH_PRECUNEUS": 2,
    "CTX_LH_SUPRAMARGINAL": 2, "CTX_RH_SUPRAMARGINAL": 2,
    "CTX_LH_LATERALOCCIPITAL": 2, "CTX_RH_LATERALOCCIPITAL": 2,
    "CTX_LH_CUNEUS": 2, "CTX_RH_CUNEUS": 2,
    "CTX_LH_PERICALCARINE": 2, "CTX_RH_PERICALCARINE": 2,
    "CTX_LH_SUPERIORFRONTAL": 2, "CTX_RH_SUPERIORFRONTAL": 2,
    "CTX_LH_ROSTRALMIDDLEFRONTAL": 2, "CTX_RH_ROSTRALMIDDLEFRONTAL": 2,
    "CTX_LH_CAUDALMIDDLEFRONTAL": 2, "CTX_RH_CAUDALMIDDLEFRONTAL": 2,
    "CTX_LH_PARSOPERCULARIS": 2, "CTX_RH_PARSOPERCULARIS": 2,
    "CTX_LH_PARSORBITALIS": 2, "CTX_RH_PARSORBITALIS": 2,
    "CTX_LH_PARSTRIANGULARIS": 2, "CTX_RH_PARSTRIANGULARIS": 2,
    "CTX_LH_LATERALORBITOFRONTAL": 2, "CTX_RH_LATERALORBITOFRONTAL": 2,
    "CTX_LH_MEDIALORBITOFRONTAL": 2, "CTX_RH_MEDIALORBITOFRONTAL": 2,
    "CTX_LH_FRONTALPOLE": 2, "CTX_RH_FRONTALPOLE": 2,
    "CTX_LH_PRECENTRAL": 2, "CTX_RH_PRECENTRAL": 2,
    "CTX_LH_POSTCENTRAL": 2, "CTX_RH_POSTCENTRAL": 2,
    "CTX_LH_PARACENTRAL": 2, "CTX_RH_PARACENTRAL": 2,
    "CTX_LH_SUPERIORTEMPORAL": 2, "CTX_RH_SUPERIORTEMPORAL": 2,
    "CTX_LH_CAUDALANTERIORCINGULATE": 2, "CTX_RH_CAUDALANTERIORCINGULATE": 2,
    "CTX_LH_ROSTRALANTERIORCINGULATE": 2, "CTX_RH_ROSTRALANTERIORCINGULATE": 2,
}


def validate_lookup():
    """Confirm every ST code maps to a region with a Braak stage."""
    missing = []
    for st, region in ST_TO_SUVR_REGION.items():
        if region not in REGION_TO_BRAAK:
            missing.append((st, region))
    if missing:
        raise ValueError(f"Missing Braak stage for: {missing}")
    print(f"Validated {len(ST_TO_SUVR_REGION)} ST codes mapped to regions and Braak stages")
    return True


if __name__ == "__main__":
    validate_lookup()